apiVersion: v1
kind: Pod
metadata:
  name: my-pod 
  labels: 
   app: xyz-app 
spec:
  containers:
  - name: my-pod-container 
    image: nginx
    ports:
      - name: http
        protocol: TCP
<<<<<<< HEAD
        containerPort: 80
=======
        containerPort: 80 
>>>>>>> 2fb29b14e0fa41cff4598ced96d72dd662b7bb74
        